Views
Tumworobere/My-Blog-App pull request #6
Opened 2022-03-31 20:40 UTC by Tumworobere

**In this project, I achieved the following:**

   - Implemented the design from the sneak peek wireframes
   - Made sure everything functions good.
   - Used the custom created methods.

2022-03-31 20:57 UTC, AshakaE requested changes
Hi @Tumworobere  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-31 20:57 UTC, AshakaE commented on app/controllers/posts_controller.rb
> +  end
The Index method is supposed to show all users, this allows current user to all other user's posts.

- [ ] Kindly update index method

2022-03-31 20:57 UTC, AshakaE commented on app/views/users/show.html.erb
> +  </ul>
- [ ] Kindly update action view `show` to display recent posts for the current user

2022-04-01 15:08 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @Tumworobere, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 15:14 UTC, Tumworobere commented
> Hi 👋 @Tumworobere,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @elisha2kyakpo1

2022-04-01 15:14 UTC, merged